### ISSUE TITLE
Consider decreasing the Max-Age of RSS feeds

### ISSUE THREAD

**Issue by skuzzymiglet** [Xe/site#329]
Currently, I get notified for articles on your blog the next day. I get notified for them on lobste.rs before that :)

Could the RSS caching code be changed so that the cache gets invalidated when new articles are posted?

**Comment by Xe** [comment]
I actually have it set like this for bandwidth reduction reasons. This route does [gigabytes of traffic](https://christine.website/blog/site-update-rss-bandwidth-2021-01-14). What do you think would work better? I have it set to 24 hours because I only really make one post per day and I also want it to be more calm (let the posts come to you when they do rather than having to read The Newest Thing Right Now) than other feeds.

**Comment by skuzzymiglet** [comment]
Sorry for the late reply,

It doesn't seem like you set a `last-modified`. Maybe if you used that you could do a lower Max-Age? The problem for me is I get a redundant notification the next day. It's OK but it makes adding your feed kinda redundant :)

I'm closing this issue because it's not that much of a problem, you can reopen it if you want.
